import type {
  Agent,
  AppNotification,
  Booking,
  Payment,
  Payout,
  PlatformStats,
  Property,
  PropertyPhoto,
  Rating,
  Strike,
  Suspension,
} from './types'

const agents: Agent[] = [
  {
    id: 'agent-1',
    businessName: 'Skyline Realty',
    fullName: 'Wanjiru Kamau',
    role: 'Verified Realtor',
    verificationStatus: 'VERIFIED',
    verifiedAt: '2026-02-14',
    strikeCount: 0,
    avgRating: 4.8,
    totalRatings: 42,
    completionRate: 0.96,
    joinedAt: '2025-09-01',
  },
  {
    id: 'agent-2',
    businessName: 'Coastline Homes',
    fullName: 'Hassan Omar',
    role: 'Verified Realtor',
    verificationStatus: 'VERIFIED',
    verifiedAt: '2026-01-20',
    strikeCount: 1,
    avgRating: 4.5,
    totalRatings: 18,
    completionRate: 0.89,
    joinedAt: '2025-11-12',
  },
  {
    id: 'agent-3',
    businessName: 'Urban Nest Agents',
    fullName: 'Brian Otieno',
    role: 'Realtor',
    verificationStatus: 'IN_PROGRESS',
    strikeCount: 0,
    avgRating: null,
    totalRatings: 2,
    completionRate: 0.75,
    joinedAt: '2026-04-02',
  },
]

function photos(internal: string[], external: string[]): PropertyPhoto[] {
  const out: PropertyPhoto[] = []
  internal.forEach((url, i) =>
    out.push({ id: `p-i-${i}-${url}`, url, type: 'INTERNAL', isFeatured: i === 0, order: i }),
  )
  external.forEach((url, i) =>
    out.push({
      id: `p-e-${i}-${url}`,
      url,
      type: 'EXTERNAL',
      isFeatured: false,
      order: internal.length + i,
    }),
  )
  return out
}

export const PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: '2-Bedroom Apartment in Kilimani',
    type: 'APARTMENT',
    status: 'AVAILABLE',
    price: 65000,
    bedrooms: 2,
    bathrooms: 2,
    floor: 'Floor 4',
    furnishing: 'SEMI_FURNISHED',
    locationGeneral: 'Kilimani, Nairobi',
    city: 'Nairobi',
    locationSpecific: { lat: -1.2921, lng: 36.7833, address: 'Argwings Kodhek Rd, Kilimani' },
    description:
      'A bright and airy 2-bedroom apartment in the heart of Kilimani. Walking distance to Yaya Centre, with secure parking, backup water and 24/7 security. Perfect for young professionals and small families.',
    amenities: ['Wi-Fi', 'Parking', 'Security', 'Water Tank', 'Balcony', 'Gym'],
    petPolicy: 'Negotiable',
    availableDate: '2026-06-15',
    photos: photos(
      ['/properties/apartment-kilimani.png', '/properties/townhouse-lavington.png'],
      ['/properties/exterior-building.png'],
    ),
    agent: agents[0],
    featured: true,
    views: 1240,
    updatedAt: '2026-06-02',
    distanceKm: 2.3,
  },
  {
    id: 'prop-2',
    title: 'Modern Studio in Westlands',
    type: 'STUDIO',
    status: 'AVAILABLE',
    price: 38000,
    bedrooms: 1,
    bathrooms: 1,
    floor: 'Floor 8',
    furnishing: 'FURNISHED',
    locationGeneral: 'Westlands, Nairobi',
    city: 'Nairobi',
    locationSpecific: { lat: -1.2649, lng: 36.8059, address: 'Woodvale Grove, Westlands' },
    description:
      'Fully furnished studio with high-speed fibre, rooftop gym and skyline views. Steps from Sarit Centre and the Westlands nightlife scene.',
    amenities: ['Wi-Fi', 'Gym', 'Security', 'Air Conditioning', 'Laundry Facility'],
    petPolicy: 'Pets not allowed',
    availableDate: '2026-06-10',
    photos: photos(
      ['/properties/studio-westlands.png'],
      ['/properties/exterior-building.png'],
    ),
    agent: agents[0],
    featured: true,
    views: 980,
    updatedAt: '2026-06-04',
    distanceKm: 4.1,
  },
  {
    id: 'prop-3',
    title: 'Spacious Townhouse in Lavington',
    type: 'TOWNHOUSE',
    status: 'AVAILABLE',
    price: 145000,
    bedrooms: 4,
    bathrooms: 3,
    floor: 'Ground Floor',
    furnishing: 'UNFURNISHED',
    locationGeneral: 'Lavington, Nairobi',
    city: 'Nairobi',
    locationSpecific: { lat: -1.2806, lng: 36.7667, address: 'James Gichuru Rd, Lavington' },
    description:
      'An elegant 4-bedroom townhouse in a gated community with landscaped gardens, a private compound and ample parking. Ideal for families seeking space and security.',
    amenities: ['Parking', 'Security', 'Garden / Green space', 'Water Tank', 'Pet-friendly'],
    petPolicy: 'Pets allowed',
    availableDate: '2026-07-01',
    photos: photos(
      ['/properties/townhouse-lavington.png', '/properties/apartment-kilimani.png'],
      ['/properties/exterior-building.png'],
    ),
    agent: agents[1],
    featured: true,
    views: 760,
    updatedAt: '2026-06-01',
    distanceKm: 5.8,
  },
  {
    id: 'prop-4',
    title: 'Affordable Bedsitter in Kahawa Sukari',
    type: 'BEDSITTER',
    status: 'AVAILABLE',
    price: 14000,
    bedrooms: 0,
    bathrooms: 1,
    floor: 'Floor 2',
    furnishing: 'UNFURNISHED',
    locationGeneral: 'Kahawa Sukari, Nairobi',
    city: 'Nairobi',
    locationSpecific: { lat: -1.18, lng: 36.92, address: 'Kahawa Sukari Estate' },
    description:
      'Neat and secure bedsitter ideal for students and young professionals. Reliable water supply, ample security and close to public transport.',
    amenities: ['Security', 'Water Tank', 'Parking'],
    petPolicy: 'Pets not allowed',
    availableDate: '2026-06-20',
    photos: photos(['/properties/bedsitter-kahawa.png'], ['/properties/exterior-building.png']),
    agent: agents[2],
    featured: false,
    views: 320,
    updatedAt: '2026-06-05',
    distanceKm: 12.4,
  },
  {
    id: 'prop-5',
    title: 'Luxury Maisonette in Karen',
    type: 'MAISONETTE',
    status: 'AVAILABLE',
    price: 220000,
    bedrooms: 5,
    bathrooms: 4,
    floor: 'Ground Floor',
    furnishing: 'FURNISHED',
    locationGeneral: 'Karen, Nairobi',
    city: 'Nairobi',
    locationSpecific: { lat: -1.3197, lng: 36.7062, address: 'Karen Rd, Karen' },
    description:
      'A stunning fully furnished maisonette set on half an acre in leafy Karen. Features a double-height living room, modern kitchen, staff quarters and a private garden.',
    amenities: ['Wi-Fi', 'Parking', 'Security', 'Garden / Green space', 'Pool', 'Water Tank', 'Pet-friendly'],
    petPolicy: 'Pets allowed',
    availableDate: '2026-08-01',
    photos: photos(
      ['/properties/maisonette-karen.png', '/properties/townhouse-lavington.png'],
      ['/properties/exterior-building.png'],
    ),
    agent: agents[0],
    featured: true,
    views: 540,
    updatedAt: '2026-05-30',
    distanceKm: 9.2,
  },
  {
    id: 'prop-6',
    title: 'Sea-Facing Apartment in Nyali',
    type: 'APARTMENT',
    status: 'AVAILABLE',
    price: 85000,
    bedrooms: 3,
    bathrooms: 2,
    floor: 'Floor 6',
    furnishing: 'SEMI_FURNISHED',
    locationGeneral: 'Nyali, Mombasa',
    city: 'Mombasa',
    locationSpecific: { lat: -4.0167, lng: 39.7, address: 'Links Rd, Nyali' },
    description:
      'Breezy 3-bedroom apartment with a sea-facing balcony, shared pool and gym. Minutes from Nyali beach and City Mall.',
    amenities: ['Wi-Fi', 'Pool', 'Gym', 'Parking', 'Security', 'Balcony'],
    petPolicy: 'Negotiable',
    availableDate: '2026-06-25',
    photos: photos(
      ['/properties/apartment-mombasa.png'],
      ['/properties/exterior-building.png'],
    ),
    agent: agents[1],
    featured: true,
    views: 670,
    updatedAt: '2026-06-03',
    distanceKm: 0.8,
  },
]

const today = new Date()
function daysFromNow(d: number) {
  const dt = new Date(today)
  dt.setDate(dt.getDate() + d)
  return dt.toISOString()
}

export const BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    property: PROPERTIES[0],
    tenantName: 'Test Tenant',
    status: 'PAID',
    visitDate: daysFromNow(-2),
    confirmationStatus: null,
    amount: 65000,
    createdAt: daysFromNow(-5),
    rated: false,
  },
  {
    id: 'bk-2',
    property: PROPERTIES[1],
    tenantName: 'Test Tenant',
    status: 'LOCKED',
    visitDate: daysFromNow(2),
    confirmationStatus: null,
    lockExpiresAt: daysFromNow(2),
    amount: 38000,
    createdAt: daysFromNow(-1),
  },
  {
    id: 'bk-3',
    property: PROPERTIES[3],
    tenantName: 'Test Tenant',
    status: 'PENDING',
    visitDate: daysFromNow(4),
    confirmationStatus: null,
    amount: 14000,
    createdAt: daysFromNow(0),
  },
  {
    id: 'bk-4',
    property: PROPERTIES[4],
    tenantName: 'Test Tenant',
    status: 'PAID',
    visitDate: daysFromNow(-8),
    confirmationStatus: 'VIEWED',
    amount: 220000,
    createdAt: daysFromNow(-12),
    rated: true,
  },
  {
    id: 'bk-5',
    property: PROPERTIES[5],
    tenantName: 'Test Tenant',
    status: 'CANCELLED',
    visitDate: daysFromNow(-20),
    confirmationStatus: null,
    amount: 85000,
    createdAt: daysFromNow(-25),
  },
]

export const PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    bookingId: 'bk-1',
    propertyTitle: PROPERTIES[0].title,
    amount: 65000,
    status: 'SUCCESS',
    mpesaReceipt: 'SGH7XK21LM',
    phone: '+254712345678',
    createdAt: daysFromNow(-5),
  },
  {
    id: 'pay-2',
    bookingId: 'bk-4',
    propertyTitle: PROPERTIES[4].title,
    amount: 220000,
    status: 'SUCCESS',
    mpesaReceipt: 'PLM3RT88QA',
    phone: '+254712345678',
    createdAt: daysFromNow(-12),
  },
]

export const RATINGS: Rating[] = [
  {
    id: 'rt-1',
    type: 'AGENT',
    score: 5,
    comment: 'Wanjiru was incredibly professional and punctual. Highly recommend!',
    metrics: [
      { name: 'Professionalism', score: 5 },
      { name: 'Honesty', score: 5 },
      { name: 'Punctuality', score: 4 },
    ],
    status: 'APPROVED',
    authorName: 'Test Tenant',
    targetName: 'Wanjiru Kamau',
    propertyTitle: PROPERTIES[4].title,
    isFlagged: false,
    createdAt: daysFromNow(-7),
  },
  {
    id: 'rt-2',
    type: 'PROPERTY',
    score: 4,
    comment: 'Photos matched reality. The compound was a little smaller than expected.',
    metrics: [
      { name: 'Accuracy', score: 4 },
      { name: 'Condition', score: 5 },
      { name: 'Amenities', score: 4 },
    ],
    status: 'PENDING_REVIEW',
    authorName: 'James Mwangi',
    targetName: PROPERTIES[0].title,
    propertyTitle: PROPERTIES[0].title,
    isFlagged: false,
    createdAt: daysFromNow(-3),
  },
  {
    id: 'rt-3',
    type: 'EXPERIENCE',
    score: 2,
    comment: 'This agent is a complete scam and a fraud, total waste of time!!!',
    metrics: [],
    status: 'PENDING_REVIEW',
    authorName: 'Anonymous User',
    targetName: 'Coastline Homes',
    propertyTitle: PROPERTIES[5].title,
    isFlagged: true,
    createdAt: daysFromNow(-1),
  },
]

export const STRIKES: Strike[] = [
  {
    id: 'st-1',
    agentName: 'Coastline Homes',
    violationType: 'Agent absent during scheduled visit',
    severity: 'MINOR',
    penaltyPoints: 10,
    reason: 'Tenant reported the agent did not show up for a confirmed viewing.',
    status: 'ACTIVE',
    createdAt: daysFromNow(-6),
  },
  {
    id: 'st-2',
    agentName: 'Urban Nest Agents',
    violationType: 'Inaccurate listing information',
    severity: 'MAJOR',
    penaltyPoints: 25,
    reason: 'Property photos did not match the actual unit.',
    status: 'UNDER_REVIEW',
    createdAt: daysFromNow(-3),
  },
]

export const SUSPENSIONS: Suspension[] = [
  {
    id: 'su-1',
    agentName: 'Old Town Agents',
    reason: 'Accumulated 3 major strikes within 60 days.',
    suspendedUntil: daysFromNow(20),
    isPermanent: false,
    status: 'ACTIVE',
    createdAt: daysFromNow(-4),
  },
]

export const PAYOUTS: Payout[] = [
  {
    id: 'po-1',
    propertyTitle: PROPERTIES[0].title,
    amount: 6500,
    status: 'PAID',
    mpesaTransactionId: 'QWE123RTY',
    createdAt: daysFromNow(-5),
  },
  {
    id: 'po-2',
    propertyTitle: PROPERTIES[4].title,
    amount: 22000,
    status: 'PAID',
    mpesaTransactionId: 'ASD456FGH',
    createdAt: daysFromNow(-12),
  },
  {
    id: 'po-3',
    propertyTitle: PROPERTIES[1].title,
    amount: 3800,
    status: 'PENDING',
    createdAt: daysFromNow(-1),
  },
]

export const PLATFORM_STATS: PlatformStats = {
  totalProperties: 1284,
  verifiedAgents: 312,
  totalBookings: 4870,
  totalRatings: 1920,
  ratingDistribution: { 5: 1180, 4: 460, 3: 180, 2: 60, 1: 40 },
}

export const AGENTS = agents

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: 'nt-1',
    type: 'PAYMENT',
    title: 'Payment confirmed',
    body: 'Your payment for 2-Bedroom Apartment in Kilimani was confirmed.',
    read: false,
    createdAt: daysFromNow(-5),
  },
  {
    id: 'nt-2',
    type: 'BOOKING',
    title: 'Lock expiring soon',
    body: 'Your hold on Modern Studio in Westlands expires in 2 days.',
    read: false,
    createdAt: daysFromNow(-1),
  },
  {
    id: 'nt-3',
    type: 'RATING',
    title: 'Leave a rating',
    body: 'How was your visit to Luxury Maisonette in Karen?',
    read: true,
    createdAt: daysFromNow(-8),
  },
]

export const KENYAN_AREAS = [
  { name: 'Kilimani', city: 'Nairobi', count: 184, avgPrice: 62000 },
  { name: 'Westlands', city: 'Nairobi', count: 156, avgPrice: 71000 },
  { name: 'Lavington', city: 'Nairobi', count: 98, avgPrice: 120000 },
  { name: 'Kahawa Sukari', city: 'Nairobi', count: 142, avgPrice: 22000 },
  { name: 'Karen', city: 'Nairobi', count: 64, avgPrice: 185000 },
  { name: 'Nyali', city: 'Mombasa', count: 87, avgPrice: 78000 },
]
